### ISSUE TITLE
Rotation on move around target

### ISSUE THREAD

**Issue by GrooverMD** [glscene/GLScene#8]
I'm just wondering why camera move around target can rotate more that 360 degres left and right but only 180 degrees up and down? Is this a OpenGL limitation or a GLScene oversight?

**Comment by jseling** [comment]
GLScene constraint here:
https://github.com/GLScene/GLScene/blob/a08a5ad57e8a1c41273f2578eb7a00b135e18ad6/Source/GLS.Scene.pas#L3340

Because this:
https://learnopengl.com/Getting-started/Camera#:~:text=if(pitch%20%3E%2089.0f)%0A%20%20pitch%20%3D%20%2089.0f%3B%0Aif(pitch%20%3C%20-89.0f)%0A%20%20pitch%20%3D%20-89.0f%3B

**Comment by glscene** [comment]
You can rotate DummyCube around any axes.
